shell: bash
files:
  - path: .
    name: "*.txt"
    create: echo Created a file $filename >> out.log
    change: echo Changed a file $filename >> out.log
    delete: echo Deleted a file $filename >> out.log
